### PR TITLE
Add one more digital twin book.

### PR DESCRIPTION
**Pull request by clagms**
Thanks for the great work in this repository.
I've opening this PR to add a link to a recent book I've co-authored. 
Thanks for considering.

-- 
Claudio Gomes
Assistant Professor at Aarhus University
Mail: [claudio.gomes@ece.au.dk](mailto:claudio.gomes@ece.au.dk)
LinkedIn: [www.linkedin.com/in/clagms](http://www.linkedin.com/in/clagms)
https://clagms.github.io/
Helsingforsgade 10
Office 5123-425,
Department of Electrical and Computer Engineering
Aarhus University, DK - 8200 Aarhus, Denmark

### CODE REVIEW

**Comment by szschaler** [comment]
Thanks, Claudio, for your contribution; this book should definitely make it onto the list! Can you take a look at the failed linting check and fix the issue? I can then review and approve.

**Comment by clagms** [comment]
Thank you @szschaler ! Now I think it is fixed (famous last words)

**Review by szschaler — APPROVED** [review]
LGTM

**Comment by szschaler** [comment]
Thanks, @clagms this looks good and I will merge now.

**Pull request merged**
